### ISSUE TITLE
Invoice for porting is still unpaid

### ISSUE THREAD

**Issue by Zwilla** [Zwilla/bmminer#1]
Dear Team,

the code which you ship to all bitcoin miners around the world is still unpaid!

I was sending you an invoice on 28th April 2017, which is still unpaid!

Please check this and send 95.03 BTC to this address 1GAmjXh6fidBcR4KrtEYceEV5zSCLJGn2r

Here you can get more details: https://github.com/Zwilla/bmminer/blob/master/README.md

The invoice was for porting your old cgminer 4.8 firmware into cgminer 4.9.2 and some protocol changes and optimisations. This cost me 1500 hours and you at moment nothing!

Yang Bai has the invoice inside his mailbox since 28th April 2017!!!

thx zwilla

p.s. it will be more than fair if you add some bucks for the delay!!!

https://github.com/bitmaintech/bmminer-mix/issues/3

**Comment by Zwilla** [comment]
https://github.com/bitmaintech/bmminer-mix/issues/3#issuecomment-334327074

**Comment by PiezPiedPy** [comment]
You do realise that the GPL License on this software gives Bitmain the right to use this software for free.

**Comment by Zwilla** [comment]
the hole story:

I worked out some code on community bounty, after a while they cancelled the bounty (discover it by your self)  
2. over bitcointalk I offered bitmain my optimized driver and code, to get a proof they want the code 
3. publishing the code and send it 
4. detected first the backdoor
5. Bitmain get in to trouble by loosing their credibility
6. 27th April they copy and paste the code
7. issue on copyright, they solved and proofed the code is now backdoor free 
The code yes the new firmware NOT!!!
8. I opened an issues (copy and paste without any donation)
9. They wrote to contact them to discuss private
10. get in touch with them with the result to write an invoice
11. Bitmain never answer nor paid the discussed work or invoice

And sure they can copy and paste what ever they want. But is that the right way? Really?
Cheating all the customers around the world?! Do you need a proof?

1. Open https://antpool.com
2. go to solo mining blocks
3. discover which worker founds the most blocks
4. cool you got it, it is the worker which is by the default recovered when the miner crashes

They know the ip, they got the miner mac, they know which customer has which miner mac. Have you ever read about how honestly bitmain was by sending the block reward to the honest finder?

No?! I’m also not. If you can calculate that solo blocks are worth millions. Mean get millions into there pocket form customers miners, from customers energy, from customers infrastructure.

Can they copy and past?
YES they can!
Can they put others block into their pocket?
YES they can!
Does they tell everyone firmware and software is now backdoor free!
Yes they did, but it is not!

cheers zwilla

**Comment by Zwilla** [comment]
Will close this issue. Have no nerves to discuss it anymore.

What they did is bad, how they have done more and what they do atm is more than bad.

If you have to proof your investors that only you can control the machines and no one else, contact me to get a really backdoor free firmware, mining engine and additional tools you need.

Stop blind trust!

hope samsung will deliver very fast the first bitcoin miner
